/**
 * Systemd service file generation and management for Syncthing on reMarkable.
 *
 * Creates and manages two systemd services:
 * 1. remarkable-sync.service: Runs Syncthing with memory limits
 * 2. remarkable-sync-watchdog.service: Monitors RAM and pauses sync when low
 *
 * Safety considerations:
 * - Services are Type=simple with Restart=on-failure (no aggressive restart loops)
 * - OOMScoreAdjust=500 ensures Syncthing is killed before xochitl if OOM occurs
 * - MemoryMax/MemoryHigh cgroup limits prevent runaway memory usage
 * - The watchdog checks free RAM and pauses Syncthing if below threshold
 * - Disabling: systemctl disable --now remarkable-sync remarkable-sync-watchdog
 * - Removing: rm /etc/systemd/system/remarkable-sync*.service && systemctl daemon-reload
 */

import type { SSHExecutor } from '../ssh/ssh-client';
import type { SyncConfig } from './types';
import {
  SYNCTHING_BIN_PATH,
  SYNCTHING_CONFIG_DIR,
  SYNCTHING_SERVICE_NAME,
  SYNCTHING_SERVICE_PATH,
  WATCHDOG_SERVICE_NAME,
  WATCHDOG_SERVICE_PATH,
  WATCHDOG_SCRIPT_PATH,
} from './types';
import { BridgeError, ErrorCode } from '../types/errors';
import { logger } from '../utils/logger';

/** Timeout for service management commands. */
const SERVICE_TIMEOUT_MS = 15_000;

/**
 * Generate the systemd unit file content for the Syncthing service.
 *
 * Key design choices:
 * - Runs as root (reMarkable has no user separation)
 * - MemoryHigh: soft limit that triggers reclaim pressure
 * - MemoryMax: hard limit that OOM-kills Syncthing (not xochitl)
 * - OOMScoreAdjust=500: sacrifice Syncthing before the UI process
 * - Nice=19: lowest scheduling priority
 * - IOSchedulingClass=idle: only use disk when nothing else needs it
 */
export function generateSyncthingServiceUnit(config: SyncConfig): string {
  const maxMemMB = config.resourceBudget.syncthingMaxMemoryMB;
  // Soft limit at 80% of hard limit to trigger reclaim early
  const highMemMB = Math.floor(maxMemMB * 0.8);

  return `[Unit]
Description=Syncthing file sync for reMarkable-Obsidian bridge
Documentation=https://github.com/user/remarkable-obsidian-bridge
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${SYNCTHING_BIN_PATH} serve --no-browser --no-restart --home=${SYNCTHING_CONFIG_DIR}
Restart=on-failure
RestartSec=30
StartLimitIntervalSec=300
StartLimitBurst=5

# Memory constraints: protect xochitl from OOM
MemoryHigh=${highMemMB}M
MemoryMax=${maxMemMB}M
OOMScoreAdjust=500

# CPU priority: be nice to xochitl
Nice=19
IOSchedulingClass=idle
IOSchedulingPriority=7

# Environment
Environment=GOMAXPROCS=1
Environment=STNOUPGRADE=1
Environment=HOME=/home/root

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Generate the memory watchdog shell script.
 *
 * This script runs in a loop, checking free RAM every 30 seconds.
 * If free RAM drops below the threshold, it pauses Syncthing by
 * stopping the service. When memory recovers, it restarts the service.
 *
 * The script is intentionally simple (pure sh, no bash-isms) because
 * the reMarkable ships with busybox ash.
 */
export function generateWatchdogScript(config: SyncConfig): string {
  const minFreeRAM = config.resourceBudget.minFreeMemoryMB;
  const checkIntervalSec = 30;
  // Recovery threshold: require 20% more free RAM than minimum before resuming
  const recoveryThresholdMB = Math.floor(minFreeRAM * 1.2);

  const lines = [
    '#!/bin/sh',
    '# Memory watchdog for reMarkable-Obsidian bridge Syncthing service.',
    `# Pauses sync when free RAM drops below ${minFreeRAM}MB.`,
    `# Resumes when free RAM recovers above ${recoveryThresholdMB}MB.`,
    '# Generated by remarkable-obsidian-bridge. Do not edit manually.',
    '',
    `SERVICE="${SYNCTHING_SERVICE_NAME}"`,
    `MIN_FREE_MB=${minFreeRAM}`,
    `RECOVERY_MB=${recoveryThresholdMB}`,
    `CHECK_INTERVAL=${checkIntervalSec}`,
    'PAUSED=0',
    '',
    'get_free_ram_mb() {',
    '    # Use MemAvailable from /proc/meminfo (includes reclaimable buffers/cache)',
    '    awk \'/^MemAvailable:/ { printf "%d", $2/1024 }\' /proc/meminfo',
    '}',
    '',
    'while true; do',
    '    FREE_MB=$(get_free_ram_mb)',
    '',
    '    if [ "$PAUSED" -eq 0 ] && [ "$FREE_MB" -lt "$MIN_FREE_MB" ]; then',
    '        echo "[watchdog] Free RAM $FREE_MB MB < $MIN_FREE_MB MB. Pausing sync."',
    '        systemctl stop "$SERVICE" 2>/dev/null',
    '        PAUSED=1',
    '    elif [ "$PAUSED" -eq 1 ] && [ "$FREE_MB" -gt "$RECOVERY_MB" ]; then',
    '        echo "[watchdog] Free RAM $FREE_MB MB > $RECOVERY_MB MB. Resuming sync."',
    '        systemctl start "$SERVICE" 2>/dev/null',
    '        PAUSED=0',
    '    fi',
    '',
    '    sleep $CHECK_INTERVAL',
    'done',
  ];
  return lines.join('\n') + '\n';
}

/**
 * Generate the systemd unit file for the memory watchdog service.
 */
export function generateWatchdogServiceUnit(): string {
  return `[Unit]
Description=Memory watchdog for reMarkable-Obsidian bridge
Documentation=https://github.com/user/remarkable-obsidian-bridge
After=${SYNCTHING_SERVICE_NAME}.service
BindsTo=${SYNCTHING_SERVICE_NAME}.service

[Service]
Type=simple
ExecStart=/bin/sh ${WATCHDOG_SCRIPT_PATH}
Restart=on-failure
RestartSec=10

# Watchdog itself uses negligible resources
Nice=19
OOMScoreAdjust=900

[Install]
WantedBy=multi-user.target
`;
}

/**
 * Deploy the Syncthing service and watchdog to the tablet.
 *
 * Writes the service unit files and watchdog script, then enables
 * and starts the services via systemd.
 *
 * @param ssh - Active SSH connection.
 * @param config - Sync configuration.
 */
export async function deployServices(
  ssh: SSHExecutor,
  config: SyncConfig,
): Promise<void> {
  logger.info('Deploying Syncthing systemd services...');

  // Ensure config directory exists
  await ssh.execute(`mkdir -p ${SYNCTHING_CONFIG_DIR}`, SERVICE_TIMEOUT_MS);

  // Write the Syncthing service unit
  const syncUnit = generateSyncthingServiceUnit(config);
  const writeResult = await ssh.execute(
    `cat > ${SYNCTHING_SERVICE_PATH} << 'SERVICEEOF'
${syncUnit}
SERVICEEOF`,
    SERVICE_TIMEOUT_MS,
  );

  if (writeResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      `Failed to write Syncthing service file to ${SYNCTHING_SERVICE_PATH}.`,
      `Error: ${writeResult.stderr}`,
    );
  }

  // Write the watchdog script
  const watchdogScript = generateWatchdogScript(config);
  const watchdogResult = await ssh.execute(
    `cat > ${WATCHDOG_SCRIPT_PATH} << 'WATCHDOGEOF'
${watchdogScript}
WATCHDOGEOF
chmod +x ${WATCHDOG_SCRIPT_PATH}`,
    SERVICE_TIMEOUT_MS,
  );

  if (watchdogResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      `Failed to write watchdog script to ${WATCHDOG_SCRIPT_PATH}.`,
      `Error: ${watchdogResult.stderr}`,
    );
  }

  // Write the watchdog service unit
  const watchdogUnit = generateWatchdogServiceUnit();
  const watchdogUnitResult = await ssh.execute(
    `cat > ${WATCHDOG_SERVICE_PATH} << 'WDSERVICEEOF'
${watchdogUnit}
WDSERVICEEOF`,
    SERVICE_TIMEOUT_MS,
  );

  if (watchdogUnitResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      `Failed to write watchdog service file to ${WATCHDOG_SERVICE_PATH}.`,
      `Error: ${watchdogUnitResult.stderr}`,
    );
  }

  // Reload systemd to pick up new unit files
  const reloadResult = await ssh.execute('systemctl daemon-reload', SERVICE_TIMEOUT_MS);
  if (reloadResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      'Failed to reload systemd daemon.',
      `Error: ${reloadResult.stderr}`,
    );
  }

  logger.info('Systemd services deployed successfully');
}

/**
 * Enable and start the Syncthing and watchdog services.
 */
export async function startServices(ssh: SSHExecutor): Promise<void> {
  logger.info('Starting Syncthing services...');

  // Enable Syncthing service (persists across reboots)
  const enableResult = await ssh.execute(
    `systemctl enable ${SYNCTHING_SERVICE_NAME}`,
    SERVICE_TIMEOUT_MS,
  );
  if (enableResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      `Failed to enable ${SYNCTHING_SERVICE_NAME} service.`,
      `Error: ${enableResult.stderr}`,
    );
  }

  // Start Syncthing service
  const startResult = await ssh.execute(
    `systemctl start ${SYNCTHING_SERVICE_NAME}`,
    SERVICE_TIMEOUT_MS,
  );
  if (startResult.exitCode !== 0) {
    throw new BridgeError(
      ErrorCode.SYNC_SERVICE_FAILED,
      `Failed to start ${SYNCTHING_SERVICE_NAME} service.`,
      `Error: ${startResult.stderr}`,
    );
  }

  // Enable and start watchdog
  const watchdogStartResult = await ssh.execute(
    `systemctl enable ${WATCHDOG_SERVICE_NAME} && systemctl start ${WATCHDOG_SERVICE_NAME}`,
    SERVICE_TIMEOUT_MS,
  );
  if (watchdogStartResult.exitCode !== 0) {
    // Watchdog failure is non-fatal -- log warning but don't throw
    logger.warn(`Failed to start watchdog service: ${watchdogStartResult.stderr}`);
  }

  logger.info('Syncthing services started');
}

/**
 * Stop and disable the Syncthing and watchdog services.
 */
export async function stopServices(ssh: SSHExecutor): Promise<void> {
  logger.info('Stopping Syncthing services...');

  // Stop both services (order: watchdog first, then Syncthing)
  await ssh.execute(
    `systemctl stop ${WATCHDOG_SERVICE_NAME} 2>/dev/null; ` +
    `systemctl disable ${WATCHDOG_SERVICE_NAME} 2>/dev/null; ` +
    `systemctl stop ${SYNCTHING_SERVICE_NAME} 2>/dev/null; ` +
    `systemctl disable ${SYNCTHING_SERVICE_NAME} 2>/dev/null`,
    SERVICE_TIMEOUT_MS,
  );

  logger.info('Syncthing services stopped');
}

/**
 * Check whether the Syncthing service is currently running.
 */
export async function isServiceRunning(ssh: SSHExecutor): Promise<boolean> {
  const result = await ssh.execute(
    `systemctl is-active ${SYNCTHING_SERVICE_NAME} 2>/dev/null`,
    SERVICE_TIMEOUT_MS,
  );
  return result.exitCode === 0 && result.stdout.trim() === 'active';
}

/**
 * Get the current RSS memory usage of the Syncthing process in MB.
 *
 * @returns RSS in MB, or null if Syncthing is not running.
 */
export async function getSyncthingMemoryUsage(ssh: SSHExecutor): Promise<number | null> {
  const result = await ssh.execute(
    `ps -o rss= -C syncthing 2>/dev/null | awk '{sum+=$1} END {if(NR>0) printf "%d", sum/1024; else print "none"}'`,
    SERVICE_TIMEOUT_MS,
  );

  if (result.exitCode !== 0 || result.stdout.trim() === 'none' || !result.stdout.trim()) {
    return null;
  }

  const rss = parseInt(result.stdout.trim(), 10);
  return isNaN(rss) ? null : rss;
}

/**
 * Remove all service files from the tablet.
 *
 * This is the cleanup step for uninstallation. Stops services first.
 */
export async function removeServices(ssh: SSHExecutor): Promise<void> {
  logger.info('Removing Syncthing service files...');

  await stopServices(ssh);

  await ssh.execute(
    `rm -f ${SYNCTHING_SERVICE_PATH} ${WATCHDOG_SERVICE_PATH} ${WATCHDOG_SCRIPT_PATH} && ` +
    'systemctl daemon-reload',
    SERVICE_TIMEOUT_MS,
  );

  logger.info('Syncthing service files removed');
}
